#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Feb  8 17:34:48 2019

@author: tompritsky
"""

import primer3

bp_sequence = "AAAAAACACCCCCCCAAAATGAA"
hairpin_parameters = primer3.calcHairpin(bp_sequence)
print(hairpin_parameters.tm) 
print(hairpin_parameters.dg)